name: Clojure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: clojure:openjdk-11-tools-deps

    steps:
    - uses: actions/checkout@v2
    - name: Build Jar archive
      working-directory: ./backend
      run: ./package.sh
    - name: Archive the jar archive
      uses: actions/upload-artifact@v2
      with:
        name: rehearser.jar
        path: backend/target/rehearser.jar
