name: Clojure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: clojure:openjdk-11-tools-deps

    steps:
    - uses: actions/checkout@v2

    - name: Check if dependencies have changed
      run: ./check-deps.sh

    - name: Run tests
      run: clojure -M:test

    - name: Build Jar archive
      run: ./package.sh

    - name: Check that the jar can at least run the main entry point
      run: java -jar target/rehearser.jar --help

    - name: Archive the jar archive
      uses: actions/upload-artifact@v2
      with:
        name: rehearser.jar
        path: target/rehearser.jar
