name: Clojure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: clojure:temurin-21-tools-deps-trixie-slim
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Check if dependencies have changed
      run: ./check-deps.sh

    - name: Run tests
      run: clojure -M:test
      env:
        POSTGRES_HOST: postgres

    - name: Build Jar archive
      run: ./package.sh

    - name: Check that the jar can at least run the main entry point
      run: java -jar target/rehearser.jar --help

    - name: Archive the jar archive
      uses: actions/upload-artifact@v4
      with:
        name: rehearser.jar
        path: target/rehearser.jar
