name: Release

on:
  push:
    tags:
      - 'rehearser-v*'

jobs:
  build-and-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    container:
      image: clojure:temurin-21-tools-deps-trixie-slim

    steps:
    - uses: actions/checkout@v4

    - name: Build release archive
      run: ./package.sh

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload rehearser.jar into the release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: target/rehearser.jar
        asset_name: rehearser.jar
        asset_content_type: application/java-archive
